server {
    listen 3000 default_server;
    server_name _;

    # Health-check for Cloudflare Container ping
    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # CDP metadata (JSON)
    location /json {
        proxy_pass http://127.0.0.1:3500;
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $server_addr;
        proxy_set_header X-Forwarded-for $server_addr;
        proxy_set_header Host '127.0.0.1';
    }

    # CDP WebSocket
    location /devtools {
        proxy_pass http://127.0.0.1:3500;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $server_addr;
        proxy_set_header X-Forwarded-for $server_addr;
        proxy_set_header Host '127.0.0.1';
    }
}
